parameters:
#    wiistriker_user.example.class: Wiistriker\UserBundle\Example

services:
#    wiistriker_user.example:
#        class: %wiistriker_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
