# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_index:
    pattern:  /
    defaults: { _controller: GovnokodCodeBundle:Code:list }
    
govnokod_code:
    resource: "@GovnokodCodeBundle/Resources/config/routing.yml"
    prefix:   /
    
govnokod_user:
    resource: "@GovnokodUserBundle/Resources/config/routing.yml"
    prefix:   /
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin