code_add:
    pattern: /add/
    defaults: { _controller: GovnokodCodeBundle:Code:save }
    
code_list:
    pattern: /{category}/
    defaults: { _controller: GovnokodCodeBundle:Code:list }

code_view:
    pattern: /{category}/{id}/
    defaults: { _controller: GovnokodCodeBundle:Code:view }
    requirements:
        id: \d+

code_view_legacy:
    pattern: /{id}
    defaults: { _controller: GovnokodCodeBundle:Code:view }
    requirements:
        id: \d+