parameters:
#    govnokod_user.example.class: Govnokod\UserBundle\Example

services:
#    govnokod_user.example:
#        class: %govnokod_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
